permalink: /:year/:month/:day/:title.html

title: Zen
description: Waiting me my love.
image: /gambar/Kyoukai_no_Kanata_1.jpg

link:
  -
    title: Play Store
    link: https://play.google.com/store/apps/dev?id=6751907367958089476
  -
    title: Email
    link: mailto:muhzaini30@gmail.com
  -
    title: Whatsapp
    link: https://wa.me/6281545143654
  -
    title: Github
    link: https://github.com/mzaini30
  -
    title: Instagram
    link: https://www.instagram.com/mzaini30/
  -
    title: Facebook
    link: https://web.facebook.com/mzaini30?_rdc=1&_rdr
  -
    title: Telegram
    link: https://t.me/mzaini30a
  -
    title: Messenger
    link: https://www.messenger.com/t/100000415959373/

banner:
  -
    image: https://2.bp.blogspot.com/-prm8pS9WO0s/WxrIbMShDOI/AAAAAAAARM4/B9ubjpiTSRcn04JwIRWVczrmf2N9mVrdwCK4BGAYYCw/s320/Logo-New-Concept-Blue.jpg
    link: http://www.warungblogger.org/
  -
    image: https://scontent.fupg1-1.fna.fbcdn.net/v/t1.0-9/34321017_2050780875240618_3875866367236243456_n.jpg?_nc_cat=101&_nc_eui2=AeE0dkCTF7rwMJqBOXeGIGkK9Iq2tSNlF7I8wyGC-Qc61EPRmQ9jZ5ctYIUE7ztGs4sFAOxbWWYrCPdkC8SyoPIMrGRa_ysc69CT6evgsgppkA&_nc_ht=scontent.fupg1-1.fna&oh=94b6bbaf8c7f8050ed5c05e02dfcce42&oe=5CC8D15F
    link: https://komunitasodop.blogspot.com/
  -
    image: https://scontent.fupg1-1.fna.fbcdn.net/v/t1.0-9/12002136_1013840355314130_4170321845040911124_n.png?_nc_cat=101&_nc_eui2=AeFLDbVUxOGidyJRQ8LFv3d1C4fa5c6PsM9nn8j5gkUuNdu4JyUNhN2MKsR5AkpjoCtRePFaOcM2Vehe4urgi3c7UMJW29HrXoa0ZluCVSEtjQ&_nc_ht=scontent.fupg1-1.fna&oh=330ca69c4b45443cdca2ac5713ae1a23&oe=5CCD38DE
    link: https://isykarima.com/
  -
    image: https://telegra.ph/file/4213cf4c0bbd55cf118c0.jpg
    link: http://lembagamitra.kemdikbud.go.id/jaring-penulis-kaltim/

paginate: 12

plugins:
  - jekyll-paginate